package Quiz;

/**
* Quiz/AnsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Quiz.idl
* Friday, 17 April, 2015 3:58:37 AM IST
*/

public final class AnsHolder implements org.omg.CORBA.portable.Streamable
{
  public Quiz.Ans value = null;

  public AnsHolder ()
  {
  }

  public AnsHolder (Quiz.Ans initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Quiz.AnsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Quiz.AnsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Quiz.AnsHelper.type ();
  }

}
