package Quiz;


/**
* Quiz/AnsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Quiz.idl
* Friday, 17 April, 2015 3:58:37 AM IST
*/

abstract public class AnsHelper
{
  private static String  _id = "IDL:Quiz/Ans:1.0";

  public static void insert (org.omg.CORBA.Any a, Quiz.Ans that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Quiz.Ans extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Quiz.AnsHelper.id (), "Ans");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Quiz.Ans read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AnsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Quiz.Ans value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Quiz.Ans narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Quiz.Ans)
      return (Quiz.Ans)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Quiz._AnsStub stub = new Quiz._AnsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Quiz.Ans unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Quiz.Ans)
      return (Quiz.Ans)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Quiz._AnsStub stub = new Quiz._AnsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
