package Quiz;


/**
* Quiz/AnsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Quiz.idl
* Friday, 17 April, 2015 3:58:37 AM IST
*/

public interface AnsOperations 
{
  int ansq (int x);
} // interface AnsOperations
